{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 1}, "tests": {"0": {"status": "ERROR", "message": "@pytest.fixture(autouse=True, scope=\"session\")\n    def authorization():  # TODO handle condition for import screens of android or ios\n        welcome_screen = WelcomeTutorialScreen(driver)\n>       welcome_screen.skip_tutorial_button()\n\n../conftest.py:76: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../src/screens/ios/welcome.py:16: in skip_tutorial_button\n    self.click_to_element(self.SKIP_TUTORIAL_BUTTON)\n../src/helpers/app.py:49: in click_to_element\n    element = self.find_element(locator)\n../src/helpers/app.py:37: in find_element\n    element = WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(locator))\n../../venv/lib/python3.8/site-packages/selenium/webdriver/support/wait.py:71: in until\n    value = method(self._driver)\n../../venv/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__\n    return _element_if_visible(_find_element(driver, self.locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <function driver at 0x7f5f43a8d1f0>, by = ('accessibility id', '\u041f\u0440\u043e\u043f\u0443\u0441\u0442\u0438\u0442\u044c')\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           AttributeError: 'function' object has no attribute 'find_element'\n\n../../venv/lib/python3.8/site-packages/selenium/webdriver/support/expected_conditions.py:411: AttributeError\n", "test_name": "test_appointment_online", "rerun": "0"}}, "suite_name": "tests/test_appointment_online.py"}}}, "date": "September 16, 2022", "start_time": 1663276637.6117249, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "0", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "1"}